// =========================================================================================
//  CRM Entity: Contact
//  This is a generated file, generated by XrmSdk.TSEntityClassGenerator, 
//  developed by Peder Moeller Wagner, ProActive (http://en.proactive.dk)
//  ProActive is a Microsoft Gold Partner, and one of the leading MS CRM partners in Denmark
//
//  Project: https://github.com/pederwagner/XrmSdkWebAPI
// =========================================================================================

/// <reference path="../../XrmSdk.WebApi/XrmSdk.Interfaces.d.ts" />
"use strict";
module XrmSdk.ContactAttributeNames {

    export var AccountId: string = "accountid";
    export var AccountRoleCode: string = "accountrolecode";
    export var Address1_AddressId: string = "address1_addressid";
    export var Address1_AddressTypeCode: string = "address1_addresstypecode";
    export var Address1_City: string = "address1_city";
    export var Address1_Composite: string = "address1_composite";
    export var Address1_Country: string = "address1_country";
    export var Address1_County: string = "address1_county";
    export var Address1_Fax: string = "address1_fax";
    export var Address1_FreightTermsCode: string = "address1_freighttermscode";
    export var Address1_Latitude: string = "address1_latitude";
    export var Address1_Line1: string = "address1_line1";
    export var Address1_Line2: string = "address1_line2";
    export var Address1_Line3: string = "address1_line3";
    export var Address1_Longitude: string = "address1_longitude";
    export var Address1_Name: string = "address1_name";
    export var Address1_PostalCode: string = "address1_postalcode";
    export var Address1_PostOfficeBox: string = "address1_postofficebox";
    export var Address1_PrimaryContactName: string = "address1_primarycontactname";
    export var Address1_ShippingMethodCode: string = "address1_shippingmethodcode";
    export var Address1_StateOrProvince: string = "address1_stateorprovince";
    export var Address1_Telephone1: string = "address1_telephone1";
    export var Address1_Telephone2: string = "address1_telephone2";
    export var Address1_Telephone3: string = "address1_telephone3";
    export var Address1_UPSZone: string = "address1_upszone";
    export var Address1_UTCOffset: string = "address1_utcoffset";
    export var Address2_AddressId: string = "address2_addressid";
    export var Address2_AddressTypeCode: string = "address2_addresstypecode";
    export var Address2_City: string = "address2_city";
    export var Address2_Composite: string = "address2_composite";
    export var Address2_Country: string = "address2_country";
    export var Address2_County: string = "address2_county";
    export var Address2_Fax: string = "address2_fax";
    export var Address2_FreightTermsCode: string = "address2_freighttermscode";
    export var Address2_Latitude: string = "address2_latitude";
    export var Address2_Line1: string = "address2_line1";
    export var Address2_Line2: string = "address2_line2";
    export var Address2_Line3: string = "address2_line3";
    export var Address2_Longitude: string = "address2_longitude";
    export var Address2_Name: string = "address2_name";
    export var Address2_PostalCode: string = "address2_postalcode";
    export var Address2_PostOfficeBox: string = "address2_postofficebox";
    export var Address2_PrimaryContactName: string = "address2_primarycontactname";
    export var Address2_ShippingMethodCode: string = "address2_shippingmethodcode";
    export var Address2_StateOrProvince: string = "address2_stateorprovince";
    export var Address2_Telephone1: string = "address2_telephone1";
    export var Address2_Telephone2: string = "address2_telephone2";
    export var Address2_Telephone3: string = "address2_telephone3";
    export var Address2_UPSZone: string = "address2_upszone";
    export var Address2_UTCOffset: string = "address2_utcoffset";
    export var Address3_AddressId: string = "address3_addressid";
    export var Address3_AddressTypeCode: string = "address3_addresstypecode";
    export var Address3_City: string = "address3_city";
    export var Address3_Composite: string = "address3_composite";
    export var Address3_Country: string = "address3_country";
    export var Address3_County: string = "address3_county";
    export var Address3_Fax: string = "address3_fax";
    export var Address3_FreightTermsCode: string = "address3_freighttermscode";
    export var Address3_Latitude: string = "address3_latitude";
    export var Address3_Line1: string = "address3_line1";
    export var Address3_Line2: string = "address3_line2";
    export var Address3_Line3: string = "address3_line3";
    export var Address3_Longitude: string = "address3_longitude";
    export var Address3_Name: string = "address3_name";
    export var Address3_PostalCode: string = "address3_postalcode";
    export var Address3_PostOfficeBox: string = "address3_postofficebox";
    export var Address3_PrimaryContactName: string = "address3_primarycontactname";
    export var Address3_ShippingMethodCode: string = "address3_shippingmethodcode";
    export var Address3_StateOrProvince: string = "address3_stateorprovince";
    export var Address3_Telephone1: string = "address3_telephone1";
    export var Address3_Telephone2: string = "address3_telephone2";
    export var Address3_Telephone3: string = "address3_telephone3";
    export var Address3_UPSZone: string = "address3_upszone";
    export var Address3_UTCOffset: string = "address3_utcoffset";
    export var Aging30: string = "aging30";
    export var Aging30_Base: string = "aging30_base";
    export var Aging60: string = "aging60";
    export var Aging60_Base: string = "aging60_base";
    export var Aging90: string = "aging90";
    export var Aging90_Base: string = "aging90_base";
    export var Anniversary: string = "anniversary";
    export var AnnualIncome: string = "annualincome";
    export var AnnualIncome_Base: string = "annualincome_base";
    export var AssistantName: string = "assistantname";
    export var AssistantPhone: string = "assistantphone";
    export var BirthDate: string = "birthdate";
    export var Business2: string = "business2";
    export var Callback: string = "callback";
    export var ChildrensNames: string = "childrensnames";
    export var Company: string = "company";
    export var ContactId: string = "contactid";
    export var CreatedBy: string = "createdby";
    export var CreatedByExternalParty: string = "createdbyexternalparty";
    export var CreatedOn: string = "createdon";
    export var CreatedOnBehalfBy: string = "createdonbehalfby";
    export var CreditLimit: string = "creditlimit";
    export var CreditLimit_Base: string = "creditlimit_base";
    export var CreditOnHold: string = "creditonhold";
    export var CustomerSizeCode: string = "customersizecode";
    export var CustomerTypeCode: string = "customertypecode";
    export var DefaultPriceLevelId: string = "defaultpricelevelid";
    export var Department: string = "department";
    export var Description: string = "description";
    export var DoNotBulkEMail: string = "donotbulkemail";
    export var DoNotBulkPostalMail: string = "donotbulkpostalmail";
    export var DoNotEMail: string = "donotemail";
    export var DoNotFax: string = "donotfax";
    export var DoNotPhone: string = "donotphone";
    export var DoNotPostalMail: string = "donotpostalmail";
    export var DoNotSendMM: string = "donotsendmm";
    export var EducationCode: string = "educationcode";
    export var EMailAddress1: string = "emailaddress1";
    export var EMailAddress2: string = "emailaddress2";
    export var EMailAddress3: string = "emailaddress3";
    export var EmployeeId: string = "employeeid";
    export var EntityImageId: string = "entityimageid";
    export var ExchangeRate: string = "exchangerate";
    export var ExternalUserIdentifier: string = "externaluseridentifier";
    export var FamilyStatusCode: string = "familystatuscode";
    export var Fax: string = "fax";
    export var FirstName: string = "firstname";
    export var FtpSiteUrl: string = "ftpsiteurl";
    export var FullName: string = "fullname";
    export var GenderCode: string = "gendercode";
    export var GovernmentId: string = "governmentid";
    export var HasChildrenCode: string = "haschildrencode";
    export var Home2: string = "home2";
    export var ImportSequenceNumber: string = "importsequencenumber";
    export var IsBackofficeCustomer: string = "isbackofficecustomer";
    export var JobTitle: string = "jobtitle";
    export var LastName: string = "lastname";
    export var LastUsedInCampaign: string = "lastusedincampaign";
    export var LeadSourceCode: string = "leadsourcecode";
    export var ManagerName: string = "managername";
    export var ManagerPhone: string = "managerphone";
    export var MasterId: string = "masterid";
    export var Merged: string = "merged";
    export var MiddleName: string = "middlename";
    export var MobilePhone: string = "mobilephone";
    export var ModifiedBy: string = "modifiedby";
    export var ModifiedByExternalParty: string = "modifiedbyexternalparty";
    export var ModifiedOn: string = "modifiedon";
    export var ModifiedOnBehalfBy: string = "modifiedonbehalfby";
    export var NickName: string = "nickname";
    export var NumberOfChildren: string = "numberofchildren";
    export var OriginatingLeadId: string = "originatingleadid";
    export var OverriddenCreatedOn: string = "overriddencreatedon";
    export var OwnerId: string = "ownerid";
    export var OwningBusinessUnit: string = "owningbusinessunit";
    export var OwningTeam: string = "owningteam";
    export var OwningUser: string = "owninguser";
    export var Pager: string = "pager";
    export var ParentContactId: string = "parentcontactid";
    export var ParentCustomerId: string = "parentcustomerid";
    export var ParticipatesInWorkflow: string = "participatesinworkflow";
    export var PaymentTermsCode: string = "paymenttermscode";
    export var PreferredAppointmentDayCode: string = "preferredappointmentdaycode";
    export var PreferredAppointmentTimeCode: string = "preferredappointmenttimecode";
    export var PreferredContactMethodCode: string = "preferredcontactmethodcode";
    export var PreferredEquipmentId: string = "preferredequipmentid";
    export var PreferredServiceId: string = "preferredserviceid";
    export var PreferredSystemUserId: string = "preferredsystemuserid";
    export var ProcessId: string = "processid";
    export var Salutation: string = "salutation";
    export var ShippingMethodCode: string = "shippingmethodcode";
    export var SpousesName: string = "spousesname";
    export var StageId: string = "stageid";
    export var StateCode: string = "statecode";
    export var StatusCode: string = "statuscode";
    export var Suffix: string = "suffix";
    export var Telephone1: string = "telephone1";
    export var Telephone2: string = "telephone2";
    export var Telephone3: string = "telephone3";
    export var TerritoryCode: string = "territorycode";
    export var TimeZoneRuleVersionNumber: string = "timezoneruleversionnumber";
    export var TransactionCurrencyId: string = "transactioncurrencyid";
    export var TraversedPath: string = "traversedpath";
    export var UTCConversionTimeZoneCode: string = "utcconversiontimezonecode";
    export var VersionNumber: string = "versionnumber";
    export var WebSiteUrl: string = "websiteurl";
    export var YomiFirstName: string = "yomifirstname";
    export var YomiFullName: string = "yomifullname";
    export var YomiLastName: string = "yomilastname";
    export var YomiMiddleName: string = "yomimiddlename";
}

module XrmSdk.ContactOptionSetValues {

    export var AccountRoleCodeValues: any = {
        Beslutningstager: 1,
        Medarbejder: 2,
        Person_der_oever_indflydelse: 3
    }

    export var Address1_AddressTypeCodeValues: any = {
        Faktura_til: 1,
        Lever_til: 2,
        Primaer: 3,
        Andet: 4
    }

    export var Address1_FreightTermsCodeValues: any = {
        FOB: 1,
        Uden_beregning: 2
    }

    export var Address1_ShippingMethodCodeValues: any = {
        Luftfragt: 1,
        DHL: 2,
        FedEx: 3,
        UPS: 4,
        Alm_post: 5,
        Andet: 8
    }

    export var Address2_AddressTypeCodeValues: any = {
        Standardvaerdi: 1
    }

    export var Address2_FreightTermsCodeValues: any = {
        Standardvaerdi: 1
    }

    export var Address2_ShippingMethodCodeValues: any = {
        Standardvaerdi: 1
    }

    export var Address3_AddressTypeCodeValues: any = {
        Standardvaerdi: 1
    }

    export var Address3_FreightTermsCodeValues: any = {
        Standardvaerdi: 1
    }

    export var Address3_ShippingMethodCodeValues: any = {
        Standardvaerdi: 1
    }

    export var CustomerSizeCodeValues: any = {
        Standardvaerdi: 1
    }

    export var CustomerTypeCodeValues: any = {
        Standardvaerdi: 1
    }

    export var EducationCodeValues: any = {
        Standardvaerdi: 1
    }

    export var FamilyStatusCodeValues: any = {
        Single: 1,
        Gift: 2,
        Skilt: 3,
        Enkestand: 4
    }

    export var GenderCodeValues: any = {
        Mand: 1,
        Kvinde: 2
    }

    export var HasChildrenCodeValues: any = {
        Standardvaerdi: 1
    }

    export var LeadSourceCodeValues: any = {
        Standardvaerdi: 1
    }

    export var PaymentTermsCodeValues: any = {
        Netto_30_dage: 1,
        Netto_8_dage: 6,
        Netto_14_dage: 7,
        Netto_kontant: 10,
        Loebende_maaned___14_dage: 11,
        Loebende_maaned___8_dage: 12
    }

    export var PreferredAppointmentDayCodeValues: any = {
        Soendag: 0,
        Mandag: 1,
        Tirsdag: 2,
        Onsdag: 3,
        Torsdag: 4,
        Fredag: 5,
        Loerdag: 6
    }

    export var PreferredAppointmentTimeCodeValues: any = {
        Morgen: 1,
        Eftermiddag: 2,
        Aften: 3
    }

    export var PreferredContactMethodCodeValues: any = {
        Ethvert: 1,
        E_mail: 2,
        Telefon: 3,
        Fax: 4,
        Post: 5
    }

    export var ShippingMethodCodeValues: any = {
        Standardvaerdi: 1
    }

    export var TerritoryCodeValues: any = {
        Standardvaerdi: 1
    }

}

module XrmSdk {

    export class Contact implements Entity {
        [index: string]: any;
        public static get ODataType(): string { return "Microsoft.Dynamics.CRM.contact"; }
        public static get EntityDataSetName(): string { return "contacts"; }
        public static get EntityLogicalName(): string { return "contact"; }

        _accountid_value: string = undefined;
        accountrolecode: number = undefined;
        address1_addressid: string = undefined;
        address1_addresstypecode: number = undefined;
        address1_city: string = undefined;
        address1_composite: string = undefined;
        address1_country: string = undefined;
        address1_county: string = undefined;
        address1_fax: string = undefined;
        address1_freighttermscode: number = undefined;
        address1_latitude: number = undefined;
        address1_line1: string = undefined;
        address1_line2: string = undefined;
        address1_line3: string = undefined;
        address1_longitude: number = undefined;
        address1_name: string = undefined;
        address1_postalcode: string = undefined;
        address1_postofficebox: string = undefined;
        address1_primarycontactname: string = undefined;
        address1_shippingmethodcode: number = undefined;
        address1_stateorprovince: string = undefined;
        address1_telephone1: string = undefined;
        address1_telephone2: string = undefined;
        address1_telephone3: string = undefined;
        address1_upszone: string = undefined;
        address1_utcoffset: number = undefined;
        address2_addressid: string = undefined;
        address2_addresstypecode: number = undefined;
        address2_city: string = undefined;
        address2_composite: string = undefined;
        address2_country: string = undefined;
        address2_county: string = undefined;
        address2_fax: string = undefined;
        address2_freighttermscode: number = undefined;
        address2_latitude: number = undefined;
        address2_line1: string = undefined;
        address2_line2: string = undefined;
        address2_line3: string = undefined;
        address2_longitude: number = undefined;
        address2_name: string = undefined;
        address2_postalcode: string = undefined;
        address2_postofficebox: string = undefined;
        address2_primarycontactname: string = undefined;
        address2_shippingmethodcode: number = undefined;
        address2_stateorprovince: string = undefined;
        address2_telephone1: string = undefined;
        address2_telephone2: string = undefined;
        address2_telephone3: string = undefined;
        address2_upszone: string = undefined;
        address2_utcoffset: number = undefined;
        address3_addressid: string = undefined;
        address3_addresstypecode: number = undefined;
        address3_city: string = undefined;
        address3_composite: string = undefined;
        address3_country: string = undefined;
        address3_county: string = undefined;
        address3_fax: string = undefined;
        address3_freighttermscode: number = undefined;
        address3_latitude: number = undefined;
        address3_line1: string = undefined;
        address3_line2: string = undefined;
        address3_line3: string = undefined;
        address3_longitude: number = undefined;
        address3_name: string = undefined;
        address3_postalcode: string = undefined;
        address3_postofficebox: string = undefined;
        address3_primarycontactname: string = undefined;
        address3_shippingmethodcode: number = undefined;
        address3_stateorprovince: string = undefined;
        address3_telephone1: string = undefined;
        address3_telephone2: string = undefined;
        address3_telephone3: string = undefined;
        address3_upszone: string = undefined;
        address3_utcoffset: number = undefined;
        aging30: number = undefined;
        aging30_base: number = undefined;
        aging60: number = undefined;
        aging60_base: number = undefined;
        aging90: number = undefined;
        aging90_base: number = undefined;
        anniversary: Date = undefined;
        annualincome: number = undefined;
        annualincome_base: number = undefined;
        assistantname: string = undefined;
        assistantphone: string = undefined;
        birthdate: Date = undefined;
        business2: string = undefined;
        callback: string = undefined;
        childrensnames: string = undefined;
        company: string = undefined;
        contactid: string = undefined;
        _createdby_value: string = undefined;
        _createdbyexternalparty_value: string = undefined;
        createdon: Date = undefined;
        _createdonbehalfby_value: string = undefined;
        creditlimit: number = undefined;
        creditlimit_base: number = undefined;
        creditonhold: boolean = undefined;
        customersizecode: number = undefined;
        customertypecode: number = undefined;
        _defaultpricelevelid_value: string = undefined;
        department: string = undefined;
        description: string = undefined;
        donotbulkemail: boolean = undefined;
        donotbulkpostalmail: boolean = undefined;
        donotemail: boolean = undefined;
        donotfax: boolean = undefined;
        donotphone: boolean = undefined;
        donotpostalmail: boolean = undefined;
        donotsendmm: boolean = undefined;
        educationcode: number = undefined;
        emailaddress1: string = undefined;
        emailaddress2: string = undefined;
        emailaddress3: string = undefined;
        employeeid: string = undefined;
        entityimageid: string = undefined;
        exchangerate: number = undefined;
        externaluseridentifier: string = undefined;
        familystatuscode: number = undefined;
        fax: string = undefined;
        firstname: string = undefined;
        ftpsiteurl: string = undefined;
        fullname: string = undefined;
        gendercode: number = undefined;
        governmentid: string = undefined;
        haschildrencode: number = undefined;
        home2: string = undefined;
        importsequencenumber: number = undefined;
        isbackofficecustomer: boolean = undefined;
        jobtitle: string = undefined;
        lastname: string = undefined;
        lastusedincampaign: Date = undefined;
        leadsourcecode: number = undefined;
        managername: string = undefined;
        managerphone: string = undefined;
        _masterid_value: string = undefined;
        merged: boolean = undefined;
        middlename: string = undefined;
        mobilephone: string = undefined;
        _modifiedby_value: string = undefined;
        _modifiedbyexternalparty_value: string = undefined;
        modifiedon: Date = undefined;
        _modifiedonbehalfby_value: string = undefined;
        nickname: string = undefined;
        numberofchildren: number = undefined;
        _originatingleadid_value: string = undefined;
        overriddencreatedon: Date = undefined;
        _ownerid_value: string = undefined;
        _owningbusinessunit_value: string = undefined;
        _owningteam_value: string = undefined;
        _owninguser_value: string = undefined;
        pager: string = undefined;
        _parentcontactid_value: string = undefined;
        _parentcustomerid_value: string = undefined;
        participatesinworkflow: boolean = undefined;
        paymenttermscode: number = undefined;
        preferredappointmentdaycode: number = undefined;
        preferredappointmenttimecode: number = undefined;
        preferredcontactmethodcode: number = undefined;
        _preferredequipmentid_value: string = undefined;
        _preferredserviceid_value: string = undefined;
        _preferredsystemuserid_value: string = undefined;
        processid: string = undefined;
        salutation: string = undefined;
        shippingmethodcode: number = undefined;
        spousesname: string = undefined;
        stageid: string = undefined;
        statecode: number = undefined;
        statuscode: number = undefined;
        suffix: string = undefined;
        telephone1: string = undefined;
        telephone2: string = undefined;
        telephone3: string = undefined;
        territorycode: number = undefined;
        timezoneruleversionnumber: number = undefined;
        _transactioncurrencyid_value: string = undefined;
        traversedpath: string = undefined;
        utcconversiontimezonecode: number = undefined;
        versionnumber: number = undefined;
        websiteurl: string = undefined;
        yomifirstname: string = undefined;
        yomifullname: string = undefined;
        yomilastname: string = undefined;
        yomimiddlename: string = undefined;

        public static castFromEntity(entity: Entity): Contact {
            var sdkEntity = new Contact();
            for (var attribute in entity) {
                if (entity.hasOwnProperty(attribute)) {
                    sdkEntity[attribute] = entity[attribute];
                }
            }
            return sdkEntity;
        }
    }
}
